const {test}=require('node:test');const assert=require('node:assert/strict');const {getDashboardAttention}=require('../dashboard-attention');
test('new manual payment does not erase an unresolved older amount; resolving old history removes queue entry',async()=>{const rows=[{id:1,user_id:2,student_id:3,school_year:'2027-2028',student_full_name:'Test',status:'admitted',registration_fee:100,tuition_paid:1}];let history=[{id:7,user_id:2,registration_id:1,amount:null},{id:8,user_id:2,registration_id:1,amount:100,method:'check'}];const db={prepare:sql=>({all:async()=>sql.includes('FROM tuition_payments')?history:sql.includes('FROM student_registrations')?rows:[]})};let result=await getDashboardAttention(db,{role:'admin'},'2026-09-08');assert.deepEqual(result.amounts.map(p=>p.paymentId),[7]);history=history.filter(p=>p.id!==7);result=await getDashboardAttention(db,{role:'admin'},'2026-09-08');assert.equal(result.amounts.length,0);assert.equal(result.balances.length,0);});
const { correctPaymentAmount } = require('../payment-correction');
function correctionFixture() {
 const state={amount:null,audit:[],totals:[],voided:false};let fail=false;
 const db={transaction:async fn=>{const before=structuredClone(state);try{return await fn({prepare:sql=>({
 all:async()=>sql.startsWith('SELECT registration_id')?[{registration_id:1,student_id:11},{registration_id:2,student_id:12}]:sql.startsWith('SELECT id FROM students')?[{id:11},{id:12}]:[{amount:state.amount,method:'imported',paid_at:'2026-01-01'},{amount:25,method:'check'}],
 get:async()=>sql.includes('FROM tuition_payment_voids')?(state.voided?{payment_id:7}:null):sql.startsWith('SELECT * FROM tuition_payments')?{id:7,amount:state.amount}:{id:1},
 run:async(...args)=>{if(sql.startsWith('INSERT INTO tuition_payment_corrections'))state.audit.push(args);else if(sql.startsWith('UPDATE tuition_payments'))state.amount=args[0];else if(sql.startsWith('UPDATE')){if(fail)throw Error('Failed snapshot');state.totals.push(args);}else throw Error(sql);}
 })});}catch(error){Object.assign(state,before);throw error;}}};return{db,state,fail:()=>{fail=true;}};
}
test('correcting an unknown shared amount preserves one entry and refreshes every linked total',async()=>{const {db,state}=correctionFixture();await correctPaymentAmount(db,7,{amount:'100.25',original_amount:'',reason:'Verified export'},9);assert.equal(state.amount,100.25);assert.deepEqual(state.audit,[[7,null,100.25,'Verified export',9]]);assert.equal(state.totals.length,4);assert.ok(state.totals.every(t=>t[1]===125.25&&t[4]===null));await correctPaymentAmount(db,7,{amount:'100.25',original_amount:'',reason:'Retry'},9);assert.equal(state.audit.length,1);await assert.rejects(correctPaymentAmount(db,7,{amount:'110',original_amount:'',reason:'Stale form'},9),/changed/);});
test('correction validates amount, reason, void status and rolls back failed recalculation',async()=>{const f=correctionFixture();for(const amount of ['0','-1','1.001','abc'])await assert.rejects(correctPaymentAmount(f.db,7,{amount,reason:'check',original_amount:''},9),/positive/);await assert.rejects(correctPaymentAmount(f.db,7,{amount:'100',reason:' ',original_amount:''},9),/reason/);f.state.voided=true;await assert.rejects(correctPaymentAmount(f.db,7,{amount:'100',reason:'check',original_amount:''},9),/voided/);f.state.voided=false;f.fail();await assert.rejects(correctPaymentAmount(f.db,7,{amount:'100',reason:'check',original_amount:''},9),/Failed snapshot/);assert.equal(f.state.amount,null);assert.equal(f.state.audit.length,0);});
